import { Component } from '@angular/core';
import { CarFilterListComponent, Car } from '../shared/car-filter-list/car-filter-list';

@Component({
  selector: 'app-porschecarmodel',
  standalone: true,
  imports: [CarFilterListComponent],
  templateUrl: './porschecarmodel.html',
  styleUrl: './porschecarmodel.css'
})
export class PorscheCarModel {
  // ================= DATA =================
  cars: Car[] = [
    {
      name: '911 Carrera',
      image: 'assets/assetscar_911-carrera.png',
      power: 394,
      acceleration: '4.1 s',
      topSpeed: 294,
      fuel: 'Petrol',
      bodyType: 'Carrera',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2026,
      price: 120000,
      horsepower: 394
    },
    {
      name: '911 Carrera T',
      image: 'assets/assetscar_911-carrera T.png',
      power: 394,
      acceleration: '4.0 s',
      topSpeed: 294,
      fuel: 'Petrol',
      bodyType: 'Carrera',
      transmission: 'Manual',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2026,
      price: 134000,
      horsepower: 394
    },
    { 
      name: '911 Carrera S',
      image: 'assets/assetscar_911-carrera S.png',
      power: 450,
      acceleration: '3.7 s',
      topSpeed: 308,
      fuel: 'Petrol',
      bodyType: 'Carrera',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2026,
      price: 140000,
      horsepower: 450
    },
    {
      name: '911 Carrera 4S',
      image: 'assets/assetscar_911-carrera 4S.png',
      power: 450,
      acceleration: '3.6 s',
      topSpeed: 306,
      fuel: 'Petrol',
      bodyType: 'Carrera',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 148000,
      horsepower: 450
    },
    {
      name: '911 Carrera GTS',
      image: 'assets/assetscar_911-carrera GTS.webp',
      power: 541,
      acceleration: '3.0 s',
      topSpeed: 312,
      fuel: 'Petrol',
      bodyType: 'Carrera',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2026,
      price: 165000,
      horsepower: 541
    },
    {
      name: '911 Carrera 4 GTS',
      image: 'assets/assetscar_911-carrera 4 GTS.webp',
      power: 541,
      acceleration: '3.0 s',
      topSpeed: 312,
      fuel: 'Petrol',
      bodyType: 'Carrera',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2026,
      price: 173000,
      horsepower: 541
    },
    {
      name: '911 Carrera Cabriolet',
      image: 'assets/assetscar_911-carrera Cabriolet.webp',
      power: 394,
      acceleration: '4.3 s',
      topSpeed: 291,
      fuel: 'Petrol',
      bodyType: 'Carrera Cabriolet',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2026,
      price: 133000,
      horsepower: 394
    },
    {
      name: '911 Carrera T Cabriolet',
      image: 'assets/assetscar_911-carrera T Cabriolet.webp',
      power: 394,
      acceleration: '4.2 s',
      topSpeed: 291,
      fuel: 'Petrol',
      bodyType: 'Carrera Cabriolet',
      transmission: 'Manual',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2025,
      price: 147000,
      horsepower: 394
    },
    {
      name: '911 Carrera S Cabriolet',
      image: 'assets/assetscar_911-carrera S Cabriolet.webp',
      power: 450,
      acceleration: '3.9 s',
      topSpeed: 306,
      fuel: 'Petrol',
      bodyType: 'Carrera Cabriolet',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2025,
      price: 153000,
      horsepower: 450
    },
    {
      name: '911 Carrera 4S Cabriolet',
      image: 'assets/assetscar_911-carrera 4S Cabriolet.webp',
      power: 450,
      acceleration: '3.8 s',
      topSpeed: 304,
      fuel: 'Petrol',
      bodyType: 'Carrera Cabriolet',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2025,
      price: 161000,
      horsepower: 450
    },
    {
      name: '911 Carrera GTS Cabriolet',
      image: 'assets/assetscar_911-carrera GTS Cabriolet.webp',
      power: 541,
      acceleration: '3.2 s',
      topSpeed: 312,
      fuel: 'Petrol',
      bodyType: 'Carrera Cabriolet',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 178000,
      horsepower: 541
    },
    {
      name: '911 Carrera 4 GTS Cabriolet',
      image: 'assets/assetscar_911-carrera 4GTS Cabriolet.webp',
      power: 541,
      acceleration: '3.2 s',
      topSpeed: 312,
      fuel: 'Petrol',
      bodyType: 'Carrera Cabriolet',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 186000,
      horsepower: 541
    },
    {
      name: '911 Targa 4S',
      image: 'assets/assetscar_911-Targa 4S.webp',
      power: 450,
      acceleration: '3.8 s',
      topSpeed: 304,
      fuel: 'Petrol',
      bodyType: 'Targa',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 161000,
      horsepower: 450
    },
    {
      name: '911 Targa 4 GTS',
      image: 'assets/assetscar_911-Targa 4 GTS.webp',
      power: 541,
      acceleration: '3.2 s',
      topSpeed: 312,
      fuel: 'Petrol',
      bodyType: 'Targa',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 186000,
      horsepower: 541
    },
    {
      name: '911 Turbo 50 Years',
      image: 'assets/assetscar_911-Turbo 50 Years.webp',
      power: 650,
      acceleration: '2.7 s',
      topSpeed: 330,
      fuel: 'Petrol',
      bodyType: 'Turbo',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 250000,
      horsepower: 650
    },
    {
      name: '911 Turbo S',
      image: 'assets/assetscar_911-Turbo S.webp',
      power: 650,
      acceleration: '2.7 s',
      topSpeed: 330,
      fuel: 'Petrol',
      bodyType: 'Turbo',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2025,
      price: 230000,
      horsepower: 650
    },
    {
      name: '911 Turbo S Cabriolet',
      image: 'assets/assetscar_911-Turbo S Cabriolet.webp',
      power: 650,
      acceleration: '2.8 s',
      topSpeed: 330,
      fuel: 'Petrol',
      bodyType: 'Turbo Cabriolet',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2025,
      price: 243000,
      horsepower: 650
    },
    {
      name: '911 GT3',
      image: 'assets/assetscar_911-GT3.webp',
      power: 510,
      acceleration: '3.4 s',
      topSpeed: 311,
      fuel: 'Petrol',
      bodyType: 'GT',
      transmission: 'Manual',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 220000,
      horsepower: 510
    },
    {
      name: '911 GT3 with Touring Package',
      image: 'assets/assetscar_911-GT3 With Touring Package.webp',
      power: 510,
      acceleration: '3.4 s',
      topSpeed: 311,
      fuel: 'Petrol',
      bodyType: 'GT',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2024,
      price: 220000,
      horsepower: 510
    },
    {
      name: '911 GT3 RS',
      image: 'assets/assetscar_911-GT3 RS.webp',
      power: 525,
      acceleration: '3.2 s',
      topSpeed: 296,
      fuel: 'Petrol',
      bodyType: 'GT',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'europe',
      brand: 'Porsche',
      year: 2022,
      price: 260000,
      horsepower: 525
    }
  ];

}
