import { Component } from '@angular/core';
import { CarFilterListComponent, Car } from '../shared/car-filter-list/car-filter-list';

@Component({
  selector: 'app-audicarmodel',
  standalone: true,
  imports: [CarFilterListComponent],
  templateUrl: './audicarmodel.html',
  styleUrl: './audicarmodel.css',
})
export class Audicarmodel {
  cars: Car[] = [
    {
      name: 'Audi A3',
      image: 'assets/assetsa3.webp',
      power: 201,
      acceleration: '7.1 s',
      topSpeed: 210,
      fuel: 'Petrol',
      bodyType: 'A3',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 36000,
      horsepower: 201
    },
    {
      name: 'Audi A3 Sportback',
      image: 'assets/assetsa3sportback.webp',
      power: 201,
      acceleration: '7.1 s',
      topSpeed: 210,
      fuel: 'Petrol',
      bodyType: 'A3',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 37000,
      horsepower: 201
    },
    {
      name: 'Audi A4',
      image: 'assets/assetsa4.png',
      power: 261,
      acceleration: '5.2 s',
      topSpeed: 210,
      fuel: 'Petrol',
      bodyType: 'A4',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 42000,
      horsepower: 261
    },
    {
      name: 'Audi A8',
      image: 'assets/assetsa8.webp',
      power: 335,
      acceleration: '5.6 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'A8',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 90000,
      horsepower: 335
    },
    {
      name: 'Audi Q3',
      image: 'assets/assetsq3.webp',
      power: 228,
      acceleration: '7.0 s',
      topSpeed: 210,
      fuel: 'Petrol',
      bodyType: 'Q3',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 38000,
      horsepower: 228
    },
    {
      name: 'Audi Q3 Sportback',
      image: 'assets/assetsq3sportback.webp',
      power: 228,
      acceleration: '7.0 s',
      topSpeed: 210,
      fuel: 'Petrol',
      bodyType: 'Q3',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 39500,
      horsepower: 228
    },
    {
      name: 'Audi Q5',
      image: 'assets/assetsq5.webp',
      power: 261,
      acceleration: '5.7 s',
      topSpeed: 220,
      fuel: 'Petrol',
      bodyType: 'Q5',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 45000,
      horsepower: 261
    },
    {
      name: 'Audi Q6 e-tron',
      image: 'assets/assetsq6etron.webp',
      power: 382,
      acceleration: '5.9 s',
      topSpeed: 210,
      fuel: 'Electric',
      bodyType: 'Q6 e-tron',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 66000,
      horsepower: 382
    },
    {
      name: 'Audi Q7',
      image: 'assets/assetsq7.webp',
      power: 335,
      acceleration: '5.6 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Q7',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 60000,
      horsepower: 335
    },
    {
      name: 'Audi Q8',
      image: 'assets/assetsq8.webp',
      power: 335,
      acceleration: '5.6 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Q8',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 74000,
      horsepower: 335
    },
    {
      name: 'Audi R8 Coupe',
      image: 'assets/assetsr8.png',
      power: 602,
      acceleration: '3.1 s',
      topSpeed: 331,
      fuel: 'Petrol',
      bodyType: 'R8',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 160000,
      horsepower: 602
    },
    {
      name: 'Audi e-tron GT',
      image: 'assets/assetsetrongt.webp',
      power: 522,
      acceleration: '3.9 s',
      topSpeed: 245,
      fuel: 'Electric',
      bodyType: 'e-tron GT',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 105000,
      horsepower: 522
    },
    {
      name: 'Audi RS3 Limousine',
      image: 'assets/assetsrs3limousine.webp',
      power: 401,
      acceleration: '3.6 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'RS3',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 62000,
      horsepower: 401
    },
    {
      name: 'Audi RS3 Sportback',
      image: 'assets/assetsrs3.webp',
      power: 401,
      acceleration: '3.6 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'RS3',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'Audi',
      year: 2023,
      price: 61500,
      horsepower: 401
    }
  ];
}
