import { Component } from '@angular/core';
import { CarFilterListComponent, Car } from '../shared/car-filter-list/car-filter-list';

@Component({
  selector: 'app-alfa-romeo-car-model',
  standalone: true,
  imports: [CarFilterListComponent],
  templateUrl: './alfa-romeo-car-model.html',
  styleUrl: './alfa-romeo-car-model.css',
})
export class AlfaRomeoCarModel {
  cars: Car[] = [
    {
      name: 'Tonale Hybrid Sprint',
      image: 'assets/assets alfaromeo tonale.png',
      power: 256,
      acceleration: '6.0 s',
      topSpeed: 206,
      fuel: 'Hybrid',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 43000,
      horsepower: 256
    },
    {
      name: 'Tonale Hybrid Ti',
      image: 'assets/assets alfaromeo tonale.png',
      power: 256,
      acceleration: '6.0 s',
      topSpeed: 206,
      fuel: 'Hybrid',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 46500,
      horsepower: 256
    },
    {
      name: 'Tonale Hybrid Veloce',
      image: 'assets/assets alfaromeo tonale.png',
      power: 256,
      acceleration: '6.0 s',
      topSpeed: 206,
      fuel: 'Hybrid',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 49600,
      horsepower: 256
    },
    {
      name: 'Stelvio Sprint',
      image: 'assets/assets alfaromeo stelvio.png',
      power: 280,
      acceleration: '5.5 s',
      topSpeed: 231,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 46000,
      horsepower: 280
    },
    {
      name: 'Stelvio Ti',
      image: 'assets/assets alfaromeo stelvio.png',
      power: 280,
      acceleration: '5.5 s',
      topSpeed: 231,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 51000,
      horsepower: 280
    },
    {
      name: 'Stelvio Veloce',
      image: 'assets/assets alfaromeo stelvio.png',
      power: 280,
      acceleration: '5.5 s',
      topSpeed: 231,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 53000,
      horsepower: 280
    },
    {
      name: 'Stelvio Quadrifoglio',
      image: 'assets/assets alfaromeo stelvio quadrifoglio.png',
      power: 505,
      acceleration: '3.6 s',
      topSpeed: 283,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 88000,
      horsepower: 505
    },
    {
      name: 'Giulia Sprint',
      image: 'assets/assets alfaromeo giulia.png',
      power: 280,
      acceleration: '5.1 s',
      topSpeed: 240,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 43500,
      horsepower: 280
    },
    {
      name: 'Giulia Ti',
      image: 'assets/assets alfaromeo giulia.png',
      power: 280,
      acceleration: '5.1 s',
      topSpeed: 240,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 46000,
      horsepower: 280
    },
    {
      name: 'Giulia Veloce',
      image: 'assets/assets alfaromeo giulia.png',
      power: 280,
      acceleration: '5.1 s',
      topSpeed: 240,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 49000,
      horsepower: 280
    },
    {
      name: 'Giulia Quadrifoglio',
      image: 'assets/assets alfaromeo giulia quadrifoglio.png',
      power: 505,
      acceleration: '3.8 s',
      topSpeed: 307,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Italy',
      brand: 'Alfa Romeo',
      year: 2024,
      price: 81000,
      horsepower: 505
    }
  ];
}
