import { Component } from '@angular/core';
import { CarFilterListComponent, Car } from '../shared/car-filter-list/car-filter-list';

@Component({
  selector: 'app-bmwcarmodel',
  standalone: true,
  imports: [CarFilterListComponent],
  templateUrl: './bmwcarmodel.html',
  styleUrl: './bmwcarmodel.css',
})
export class Bmwcarmodel {
  cars: Car[] = [
    {
      id: 'bmw3series',
      name: 'BMW 3 Series',
      image: 'assets/assetsbmw340i.png',
      power: 255,
      acceleration: '5.8 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 45000,
      horsepower: 255
    },
    {
      id: 'bmw-5-series',
      name: 'BMW 5 Series',
      image: 'assets/assets5series.png',
      power: 375,
      acceleration: '4.1 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 65000,
      horsepower: 375
    },
    {
      id: 'bmw-x1',
      name: 'BMW X1',
      image: 'assets/assetsx1.png',
      power: 241,
      acceleration: '6.2 s',
      topSpeed: 210,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 40500,
      horsepower: 241
    },
    {
      id: 'bmw-x2',
      name: 'BMW X2',
      image: 'assets/assetsx2.png',
      power: 241,
      acceleration: '6.2 s',
      topSpeed: 210,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 42000,
      horsepower: 241
    },
    {
      id: 'bmw-x3',
      name: 'BMW X3',
      image: 'assets/assetsx3.png',
      power: 382,
      acceleration: '4.4 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 49000,
      horsepower: 382
    },
    {
      id: 'bmw-x5',
      name: 'BMW X5',
      image: 'assets/assetsx5.png',
      power: 375,
      acceleration: '5.2 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 67500,
      horsepower: 375
    },
    {
      id: 'bmw-x5-m60i',
      name: 'BMW X5 M60i',
      image: 'assets/assetsx5m60i.png',
      power: 523,
      acceleration: '4.2 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 90000,
      horsepower: 523
    },
    {
      id: 'bmw-x5-m-competition',
      name: 'BMW X5 M Competition',
      image: 'assets/assetsx5mcompetition.png',
      power: 617,
      acceleration: '3.7 s',
      topSpeed: 290,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 122000,
      horsepower: 617
    },
    {
      id: 'bmw-x6',
      name: 'BMW X6',
      image: 'assets/assetsx6.png',
      power: 375,
      acceleration: '5.2 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 74500,
      horsepower: 375
    },
    {
      id: 'bmw-x7',
      name: 'BMW X7',
      image: 'assets/assetsX7.png',
      power: 375,
      acceleration: '5.6 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 82000,
      horsepower: 375
    },
    {
      id: 'bmw-z4-m',
      name: 'BMW Z4 M40i',
      image: 'assets/assetsz4m.png',
      power: 382,
      acceleration: '3.9 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Convertible',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 65000,
      horsepower: 382
    },
    {
      id: 'bmw-m5',
      name: 'BMW M5',
      image: 'assets/assetsm5.png',
      power: 600,
      acceleration: '3.2 s',
      topSpeed: 305,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 110000,
      horsepower: 600
    },
    {
      id: 'bmw-340i-m',
      name: 'BMW M340i - xDrive',
      image: 'assets/assetsbmw340iM.png',
      power: 382,
      acceleration: '4.1 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 58500,
      horsepower: 382
    },
    {
      id: 'bmwm440i',
      name: 'BMW M440i Coupe',
      image: 'assets/assetsbmw440i.png',
      power: 382,
      acceleration: '4.3 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Coupe',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 60000,
      horsepower: 382
    },
    {
      id: 'bmw-440i-convertible',
      name: 'BMW M440i Convertible',
      image: 'assets/assetsbmw440iconvertable.png',
      power: 382,
      acceleration: '4.7 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Convertible',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 68500,
      horsepower: 382
    },
    {
      id: 'bmw-440i-m',
      name: 'BMW M440i xDrive Coupe',
      image: 'assets/assetsbmw440im.png',
      power: 382,
      acceleration: '4.0 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Coupe',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2023,
      price: 62000,
      horsepower: 382
    },
    {
      id: 'bmw-i5',
      name: 'BMW i5 eDrive40',
      image: 'assets/assetsbmwi5.png',
      power: 335,
      acceleration: '5.7 s',
      topSpeed: 193,
      fuel: 'Electric',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2024,
      price: 67000,
      horsepower: 335
    },
    {
      id: 'bmw-im-740',
      name: 'BMW i7 xDrive60',
      image: 'assets/assetsbmwim740.png',
      power: 536,
      acceleration: '4.5 s',
      topSpeed: 250,
      fuel: 'Electric',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2024,
      price: 106000,
      horsepower: 536
    },
    {
      id: 'bmwm3competition',
      name: 'BMW M3 Compétition',
      image: 'assets/assetsbmwm3.png',
      power: 473,
      acceleration: '4.1 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2024,
      price: 76000,
      horsepower: 473
    },
    {
      id: 'bmwm4competition',
      name: 'BMW M4 Compétition',
      image: 'assets/assetsabmwm4.png',
      power: 473,
      acceleration: '4.1 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Coupe',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2024,
      price: 78000,
      horsepower: 473
    },
    {
      id: 'bmwm5competition',
      name: 'BMW M5 Competition',
      image: 'assets/assetsbmwm5competition (2).png',
      power: 717,
      acceleration: '3.5 s',
      topSpeed: 305,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2024,
      price: 130000,
      horsepower: 717
    },
    {
      id: 'bmw7series',
      name: 'BMW 740i',
      image: 'assets/assetsbmwm740.png',
      power: 375,
      acceleration: '5.2 s',
      topSpeed: 250,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'RWD',
      country: 'Germany',
      brand: 'BMW',
      year: 2024,
      price: 96000,
      horsepower: 375
    }
  ];
}
