import { Component } from '@angular/core';
import { CarFilterListComponent, Car } from '../shared/car-filter-list/car-filter-list';

@Component({
  selector: 'app-baiccarmodel',
  standalone: true,
  imports: [CarFilterListComponent],
  templateUrl: './baiccarmodel.html',
  styleUrl: './baiccarmodel.css',
})
export class Baiccarmodel {
  cars: Car[] = [
    {
      name: 'BAIC BJ30',
      image: 'assets/assetsbj30.png',
      power: 188,
      acceleration: '9.0 s',
      topSpeed: 170,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'AWD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 18000,
      horsepower: 188
    },
    {
      name: 'BAIC BJ40 Plus',
      image: 'assets/assetsbj40plus.png',
      power: 224,
      acceleration: '9.8 s',
      topSpeed: 160,
      fuel: 'Petrol',
      bodyType: 'Off-road',
      transmission: 'Automatic',
      driveTrain: '4WD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 23000,
      horsepower: 224
    },
    {
      name: 'BAIC BJ60',
      image: 'assets/assetsbj60.png',
      power: 261,
      acceleration: '8.5 s',
      topSpeed: 180,
      fuel: 'Petrol',
      bodyType: 'Off-road',
      transmission: 'Automatic',
      driveTrain: '4WD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 34000,
      horsepower: 261
    },
    {
      name: 'BAIC BJ80',
      image: 'assets/assetsbj80.png',
      power: 276,
      acceleration: '9.0 s',
      topSpeed: 180,
      fuel: 'Petrol',
      bodyType: 'Off-road',
      transmission: 'Automatic',
      driveTrain: '4WD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 45000,
      horsepower: 276
    },
    {
      name: 'ALL NEW X7',
      image: 'assets/assetsallnewx7.png',
      power: 188,
      acceleration: '8.8 s',
      topSpeed: 180,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 21000,
      horsepower: 188
    },
    {
      name: 'X55 II',
      image: 'assets/assetsx55ii.png',
      power: 177,
      acceleration: '7.8 s',
      topSpeed: 180,
      fuel: 'Petrol',
      bodyType: 'SUV',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 19500,
      horsepower: 177
    },
    {
      name: 'U5 Plus',
      image: 'assets/assetsu5plus.png',
      power: 113,
      acceleration: '11.5 s',
      topSpeed: 160,
      fuel: 'Petrol',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 14000,
      horsepower: 113
    },
    {
      name: 'EU5',
      image: 'assets/assetseu5.png',
      power: 163,
      acceleration: '7.8 s',
      topSpeed: 155,
      fuel: 'Electric',
      bodyType: 'Sedan',
      transmission: 'Automatic',
      driveTrain: 'FWD',
      country: 'China',
      brand: 'BAIC',
      year: 2025,
      price: 17500,
      horsepower: 163
    }
  ];
}
